spring:
  application:
    name: hrm-backend
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:HRM}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:123456}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SMTP_USERNAME:cuongtran.23092004@gmail.com}
    password: ${SMTP_PASSWORD:hkya isfh eeoj uuvv}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

app:
  jwt:
    secret: dGhpc0lzQVN1cGVyU2VjcmV0S2V5Rm9ySFJNU3lzdGVtSldUVG9rZW5HZW5lcmF0aW9uMjAyNg==
    expiration-ms: 86400000
  attendance:
    office-latitude: 10.848031  
    office-longitude: 106.784944
    allowed-radius-meters: 200.0
    allowed-ips:
      - "127.0.0.1"
      - "0:0:0:0:0:0:0:1"
      - "192.168.1.45"
      - "123.21.246.223"
